# Generated by Django 6.0.5 on 2026-05-16 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('feed_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('pdf', 'PDF'), ('mixed', 'Mixed')], db_index=True, max_length=20)),
                ('thumbnail', models.ImageField(upload_to='feeds/thumbnails/')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('total_views', models.PositiveBigIntegerField(default=0)),
                ('total_likes', models.PositiveBigIntegerField(default=0)),
                ('total_shares', models.PositiveBigIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='config.category')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='config.subcategory')),
                ('tags', models.ManyToManyField(related_name='feeds', to='config.tag')),
            ],
            options={
                'db_table': 'feeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedInternalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('source_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='feeds.feed')),
                ('target_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='feeds.feed')),
            ],
            options={
                'db_table': 'feed_internal_links',
            },
        ),
        migrations.CreateModel(
            name='FeedMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], db_index=True, max_length=20)),
                ('file', models.FileField(upload_to='feeds/media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='feeds/media/thumbs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='feeds.feed')),
            ],
            options={
                'db_table': 'feed_media',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['title'], name='feeds_title_76f322_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['feed_type'], name='feeds_feed_ty_3a92e8_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['category'], name='feeds_categor_831c03_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['subcategory'], name='feeds_subcate_f1e432_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['is_published'], name='feeds_is_publ_899107_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['created_at'], name='feeds_created_2acd37_idx'),
        ),
        migrations.AddIndex(
            model_name='feedinternallink',
            index=models.Index(fields=['keyword'], name='feed_intern_keyword_a08e01_idx'),
        ),
        migrations.AddIndex(
            model_name='feedmedia',
            index=models.Index(fields=['feed'], name='feed_media_feed_id_74b73d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedmedia',
            index=models.Index(fields=['media_type'], name='feed_media_media_t_111a63_idx'),
        ),
    ]
