"""
Django settings for socialapp project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^-$+np_ozn33wg%yb+bpsz^@m3f!tx!zmucp+v(b11$u-+b5fz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',"192.168.29.203"]


# Application definition

INSTALLED_APPS = [

    # ADMIN LTE
    'jazzmin',

    # DJANGO DEFAULT
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # LOCAL APPS
    'authentication',
    'config',
    'feeds',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'socialapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialapp.wsgi.application'

JAZZMIN_SETTINGS = {

    "site_title": "Social Learning Admin",

    "site_header": "Social Learning",

    "site_brand": "SocialApp",

    "welcome_sign": "Welcome to Social Learning Admin",

    "copyright": "Social Learning App",

    "search_model": [

        "feeds.Feed",

        "config.Category",

        "config.SubCategory",

        "config.Tag",
    ],

    "show_sidebar": True,

    "navigation_expanded": True,

    "show_ui_builder": True,

    "changeform_format": "horizontal_tabs",

    "theme": "darkly",

    "icons": {

        "auth": "fas fa-users-cog",

        "authentication.User": "fas fa-user",

        "feeds.Feed": "fas fa-newspaper",

        "config.Category": "fas fa-list",

        "config.SubCategory": "fas fa-layer-group",

        "config.Tag": "fas fa-tags",
    },
}

# JAZZMIN_UI_TWEAKS = {

#     "navbar_small_text": False,

#     "footer_small_text": False,

#     "body_small_text": False,

#     "brand_small_text": False,

#     "brand_colour": "navbar-primary",

#     "accent": "accent-primary",

#     "navbar": "navbar-dark",

#     "no_navbar_border": True,

#     "navbar_fixed": True,

#     "layout_boxed": False,

#     "footer_fixed": False,

#     "sidebar_fixed": True,

#     "sidebar": "sidebar-dark-primary",

#     "sidebar_nav_small_text": False,

#     "sidebar_disable_expand": False,

#     "sidebar_nav_child_indent": True,

#     "sidebar_nav_compact_style": False,

#     "sidebar_nav_legacy_style": False,

#     "sidebar_nav_flat_style": False,

#     "theme": "darkly",
# }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'
